### ISSUE TITLE
renameExecutables isn't set up properly as a dependency

### ISSUE THREAD

**Issue by mvdan** [Free-Software-for-Android/RootCommands#22]
`build` depends on it, but one can do the lower task `assembleRelease` to just do a release apk (without producing a debug apk and running the tests, which `build` would do) and `renameExecutables` won't be run.

**Comment by mvdan** [comment]
Oh wow, I just spent an hour trying to set up ndk with gradle for an app and found the solution I had written one year prior.

**Comment by dschuermann** [comment]
:P Sry I don't maintain this library any longer...

**Comment by mvdan** [comment]
Closing to remove it from my opened issue backlog.
